### ISSUE TITLE
Main window keeps being resized to a small geometry 

### ISSUE THREAD

**Issue by eidolies** [jasonwinning/hypernomicon#10] opened 2022-04-25 20:00 UTC
After actions such as going in the Settings or right before quiting, the main window keeps being resized to a very small geometry, too small to use the interface (316x166 in my case)

Version: 1.23.1  
Build date: 2022-04-23 20:47:28 UTC  

Operating system: Linux  
Operating system version: 5.4.0-109-generic  
Java runtime: 16.0.1+9-Ubuntu-120.04 OpenJDK Runtime Environment  
JavaFX version: 17.0.1+1

**Comment by jasonwinning** [comment] 2022-04-25 22:18
Hi, based on the information you listed it looks like your Linux distro is Ubuntu 20.04 LTS. Can you confirm that that is correct? I am unable to reproduce the problem on Fedora so I need to test it on the distro you are using.

Jason

**Comment by eidolies** [comment] 2022-04-26 00:30
The Java runtime is a Ubuntu build, yes, while I'm running Linux Mint 20.3 (based on Ubuntu) in XFCE 4.16. Same thing happens on LXQt, so probably not a DE/WM issue.

**Comment by jasonwinning** [comment] 2022-04-26 02:47
Okay I tested it in Linux Mint 20.3 with XFCE and your java version. It seems that what is happening is that after opening and closing a popup window (like Settings), it reverts the main window back to the size it was when you first started the application. As a temporary workaround try these steps: 1) Start the application. 2) Close the database if one is open (from File menu). 3) Resize the main window to desired size. 4) Exit the application and restart it. Now the application should be at the desired size (and will keep resizing it back to that). I'll try to figure out why that is happening (and why it is defaulting to a small size).

**Comment by jasonwinning** [comment] 2022-04-26 05:21
This fix will be included in version 1.24

**Closed as completed by jasonwinning** 2022-04-26 05:21 UTC
